WIP: PAPP-21105: Bug fix and feature enhancements
splunk-soar-connectors/ewsonprem pull request #6
Opened 2021-12-09 11:21 UTC by dvora-crest

Update artifact addition implementation for PAPP-18376

Add all the artifacts in a single save_artifacts() call.

2021-12-29 19:06 UTC, paulnawat commented on process_email.py
> -                curr_file, vault_ids, container_id, vault_artifacts_added, run_automation
Instead of moving all the code of `handle_file` here, what do you think about updating/renaming the helper `handle_file`?
This might help with the readability of this `_handle_save_ingested` later on..

2021-12-29 19:21 UTC, paulnawat requested changes
The changes look nice. I left a few questions / comments for now.

2021-12-29 19:21 UTC, paulnawat commented on process_email.py
>          # One of either container or container_id will be set to None
Seeing that this method is getting bigger, would it be possible to add some docstring to explain what it does?

2021-12-29 19:21 UTC, paulnawat commented on process_email.py
> -        ret_val, message, container_id = self._save_ingested(container, using_dummy)
I believe the save logic gets encapsulated into `_save_ingested` to more this method more readable. This might also help speed up debugging this method later on.
Do you think we can keep the helper and make logic updates there instead?

2021-12-29 19:21 UTC, paulnawat commented on ewsonprem_connector.py
> +                    data = resp_json['m:Items'][key]
Do we need to handle the case where data remains `None` (i.e. no matching key in the attachment_keys)?

2021-12-29 19:21 UTC, paulnawat commented on ewsonprem_connector.py
> +                    data = resp_json['m:Items'][key]
same here about if data can be None after the logic here.

2021-12-30 07:11 UTC, achandya-crest commented on process_email.py
>          # One of either container or container_id will be set to None
Added docstring and mentioned the whole workflow of the method.

2021-12-30 07:17 UTC, achandya-crest commented on process_email.py
> -        ret_val, message, container_id = self._save_ingested(container, using_dummy)
As before the save logic was implemented such that the container was first saved and then all the artifacts(except the Vault artifacts) were saved in save_ingested method. And then the ingested files were one by one saved in handle_file method.

But now the workflow has changed due to https://splunk.atlassian.net/browse/PAPP-18376 issue and the code flow goes according to this:
The container is saved without saving the artifacts into it.
Then the artifacts list (that has all artifacts except the vault artifacts) is appended with the Vault artifacts after creating vault artifacts.
All the artifacts once collected, are saved together then.

Due to this change in workflow, save_ingested method did not have any use so it was removed instead of renaming or creating a helper method out of it.

2021-12-30 19:07 UTC, paulnawat commented on process_email.py
> -        ret_val, message, container_id = self._save_ingested(container, using_dummy)
I see. Thanks!

2021-12-30 19:14 UTC, paulnawat commented on process_email.py
>          # One of either container or container_id will be set to None
super, thanks!

2021-12-30 19:20 UTC, paulnawat commented on process_email.py
> -                curr_file, vault_ids, container_id, vault_artifacts_added, run_automation
suggestion: Seeing that the method is approaching 200 lines, what do you think about extracting the loop into a helper like _add_artifacts_and_container_from_files ?
This might help us debug faster later on (i.e. it’s easier to jump over unrelated code)
I will leave this up to you.

2021-12-31 06:04 UTC, achandya-crest commented on ewsonprem_connector.py
> +                    data = resp_json['m:Items'][key]
If data is None, L2078 will throw an exception and action will pass.

2021-12-31 06:04 UTC, achandya-crest commented on ewsonprem_connector.py
> +                    data = resp_json['m:Items'][key]
If we don't get data or data is None, exception will lead to skipping L2203. And it wont create an issue as in case L2203 is not run, further if statements are added that handles the workflow.

2021-12-31 06:06 UTC, paulnawat commented on ewsonprem_connector.py
> +                    data = resp_json['m:Items'][key]
Thanks @achandya-crest  for pointing out that data being None will be handled on the next line. Resolving this and the other threads.

2021-12-31 06:07 UTC, paulnawat approved these changes
lgtm. Please help ensure the pipeline is green before merging / add the ticket where the pipeline will be fixed.

cc: @achandya-crest

2022-01-03 19:13 UTC, paulnawat approved these changes

2022-01-04 12:21 UTC, ishans-crest approved these changes

2022-01-05 05:07 UTC, merged